### PR TITLE
Iss5

### PR DESCRIPTION
**Pull request by rafopar**
A new file GenerateGenOptions.py is created which Geberates and overwrites the GenOptions.dat file with command line arguments provided by the user.

### CODE REVIEW

**Comment by rafopar** [comment]
Hi @baltzell , there is no need to go through the code (unless you you would like to do it), just testing it and checking if it creates the file with appropriate values should be enough.

p.s. I did it in my computer and it worked

**Comment by baltzell** [comment]
Build will work for me after after accepting my PR on iss5 branch.

**Comment by rafopar** [comment]
Thank you,
PR #8 is merged

**Comment by rafopar** [comment]
For minor things yes, but I though in general it is a good idea, to have someone tested, if several people might use the code

**Pull request merged**
